### ISSUE TITLE
Rails5

### ISSUE THREAD

**Issue by shu0115** [FiNCDeveloper/shortener#1]
- Rails5も、もうbeta3まで来ているので、新規開発はRails5でも良さそう
  * [Riding Rails: Rails 5.0.0.beta3: More fixes, RC1 is soon](http://weblog.rubyonrails.org/2016/2/27/Rails-5-0-beta3/)
- 既存のプロジェクトにRails5を適用する前に小さいサブプロジェクトで感触を掴めるのは良い
- GemのRails5対応も少しは検証出来るかも

**Comment by kenjiszk** [comment]
+1

**Comment by shinofumijp** [comment]
+1

**Comment by 6temes** [comment]
+1 !

**Comment by shu0115** [comment]
DONE
