### ISSUE TITLE
本url編集画面

### ISSUE THREAD

**Issue by kenjiszk** [FiNCDeveloper/shortener#19]
短縮URL作成後、本urlを編集したいという要望がたまに来る。
admin画面のように特定の人(or basic認証？)だけが、本URLを変更出来るコンソールが欲しい。

もしくは、自分の作成したurlだけ更新出来るとか。
(ユーザー登録が必要で面倒なので、pinコード的な物で簡易で実装しても良い気がする)

**Comment by shu0115** [comment]
- [[WIP]いろいろ追加／更新 by shu0115 · Pull Request #21 · FiNCDeveloper/shortener](https://github.com/FiNCDeveloper/shortener/pull/21#issuecomment-205690503)
- [Add update location page](https://github.com/FiNCDeveloper/shortener/pull/21/commits/3a8f7fc40dc8eae4f248ae666a45c81c656dc7c5)

@kenjiszk ↑こんな感じでどうでしょう？
簡易的な実装ですが、編集ページで認証キーを入力するようにして、入力値が`Settings.update_authenticate_key`と一致しなかったらエラーで返すようにしています。

https://github.com/FiNCDeveloper/shortener/pull/21/commits/3a8f7fc40dc8eae4f248ae666a45c81c656dc7c5#diff-b2b4310d1a2ee6c5549424c06c2893beR13

Productionの場合は↑ここの`UPDATE_AUTHENTICATE_KEY `という環境変数に`SecureRandom.uuid`などで生成したキーを入れてもらう想定です。
(キーを知ってる人だけが更新を行える)

確認お願いしますー。
