### ISSUE TITLE
短縮機能の社員制限

### ISSUE THREAD

**Issue by shu0115** [FiNCDeveloper/shortener#2]
- 厳密にはフリーランス、アルバイト、インターンなども使用可能だと思うので、正社員限定ではない

## 実装案

- 共有パスワード
  - 短縮機能ページへのアクセスにパスワード入力を設ける
  - パスワードが漏れると社外の人でも使える
  - 人の入れ替わりが激しいと共有パスワードを頻繁に変更する必要が出るかも
  - 共有パスワードは基本的に悪手
- IP制限
  - 特定のIPアドレスからのアクセスのみ短縮機能ページへのアクセスを許可する
  - FiNCオフィスにいないと使えない
  - 出先や社外のMTGなどで短縮URLを生成出来ない

その他？

**Comment by kenjiszk** [comment]
最初はIP制限にしましょうか。
nginxのレイヤーで短縮urlを受け付けるところ以外はIP制限をかけましょう。
出先では使えないですが、まあ社内の人に連絡して作ってもらうとか。
共有パスワードで良い未来は見えないので。

先の話ですが、vpnを整備していく予定なのでそうなったら出先でも使えるようになると思います。

**Comment by shu0115** [comment]
:+1: 

> nginxのレイヤーで短縮urlを受け付けるところ以外はIP制限をかけましょう。

じゃあ、アプリケーション側では特に何もしなくて大丈夫ですかね？

**Comment by shu0115** [comment]
https://bit.finc.com/
IP制限でDONE
